In [6]:
from data_pipeline.fetch_all_team_data import fetch_all_team_data

"""
main jupyter notebook for Ml project]
Ronan kenny 
23404724
"""

'\nmain jupyter notebook for Ml project]\nRonan kenny \n23404724\n'

In [7]:

# use module to load in the total team data and extract match statistics for all teams
team_data = fetch_all_team_data()["all_match_stats"]
#print("Team datashape:")
#print(team_data.shape)
#team_data.info()
display(team_data.iloc[0].to_frame(name="value"))
display(team_data.iloc[10].to_frame(name="value"))

Fetching all teams available...
Fetching all team stats for team_id: 34bd3e4e...
Fetching all team stats for team_id: 94c0327a...
Fetching all team stats for team_id: 67d88578...
Fetching all team stats for team_id: 165b36e5...
Fetching all team stats for team_id: bf499d89...
Fetching all team stats for team_id: 246228fc...
Fetching all team stats for team_id: d7f92ae2...
Fetching all team stats for team_id: f13dc547...
Fetching all team stats for team_id: 4409215c...
Fetching all team stats for team_id: d0cffe5e...
Fetching all team stats for team_id: b523256e...
Fetching all team stats for team_id: e9c9c61d...
Fetching all team stats for team_id: 4ec76284...
Fetching all team stats for team_id: 29dd316b...
Fetching all team stats for team_id: ad805c09...
Fetching all team stats for team_id: 94b19a71...
Fetching all team stats for team_id: a659d6d1...
Fetching all team stats for team_id: 7aca7d09...
Fetching all team stats for team_id: 18b82d15...
Fetching all team stats for team_id: 191fadb7...
Fetching all team stats for team_id: 853d7117...
Fetching all team stats for team_id: ab16e051...
Fetching all team stats for team_id: dd8c26fa...
Fetching all team stats for team_id: acc26931...
Fetching all team stats for team_id: 1e5397f3...
Fetching all team stats for team_id: 893fa1ce...
Fetching all team stats for team_id: a52b46a5...
Fetching all team stats for team_id: f16ac41b...
Fetching all team stats for team_id: ae6fad95...
Fetching all team stats for team_id: 2fd4e8bc...
Fetching all team stats for team_id: 44ca4302...
Fetching all team stats for team_id: b5c8e8c1...
Fetching all team stats for team_id: d5822444...
Fetching all team stats for team_id: 872c8a5f...
Fetching all team stats for team_id: 8b3463f1...
Fetching all team stats for team_id: d416d837...
Fetching all team stats for team_id: 19caba7a...
Fetching all team stats for team_id: 3c1ddd90...
Fetching all team stats for team_id: 3ee8bf6e...
Fetching all team stats for team_id: cc84cf10...
Fetching all team stats for team_id: 7d1506e2...
Fetching all team stats for team_id: d04bd1b8...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: e9266711...
Fetching all team stats for team_id: f60f757d...
Fetching all team stats for team_id: 9d5622fd...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: f7391250...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 0a881579...
Fetching all team stats for team_id: adac1214...
Fetching all team stats for team_id: dfd6513f...
Fetching all team stats for team_id: 05746ea3...
Fetching all team stats for team_id: a7183edf...
Fetching all team stats for team_id: 2fb1e472...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 85e672c5...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 65f03256...
Fetching all team stats for team_id: 2f057227...
Fetching all team stats for team_id: 9009af65...
Fetching all team stats for team_id: fdae13ce...
Fetching all team stats for team_id: d58f01a6...
Fetching all team stats for team_id: a525ab01...
Fetching all team stats for team_id: 25e057f2...
Fetching all team stats for team_id: e18eccaa...
Fetching all team stats for team_id: 4148a077...
Fetching all team stats for team_id: 094dae60...
Fetching all team stats for team_id: 69106d50...
Fetching all team stats for team_id: 1324eb9d...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 31c501eb...
Fetching all team stats for team_id: fed72dd1...
Fetching all team stats for team_id: 0e767076...
Fetching all team stats for team_id: 5b8a6de9...
Fetching all team stats for team_id: be4fac42...
Fetching all team stats for team_id: 6c114c99...
Fetching all team stats for team_id: f249d554...
Fetching all team stats for team_id: c618b954...
Fetching all team stats for team_id: 71db72fb...
Fetching all team stats for team_id: 85025c2e...
Fetching all team stats for team_id: a2c2c408...
Fetching all team stats for team_id: c588f47a...
Fetching all team stats for team_id: 5459e034...
Fetching all team stats for team_id: 9f5e9a0c...
Fetching all team stats for team_id: 3cb0bc07...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: ef00cb4f...
Fetching all team stats for team_id: 8c6217c0...
Fetching all team stats for team_id: 3d9ed566...
Fetching all team stats for team_id: 29cfd1d3...
Fetching all team stats for team_id: ebd7f173...
Fetching all team stats for team_id: 821a6e9b...
Fetching all team stats for team_id: 30ca1553...
Fetching all team stats for team_id: 1e02b3c3...
Fetching all team stats for team_id: 6a2502db...
Fetching all team stats for team_id: 3c4f2505...
Fetching all team stats for team_id: bd69e43e...
Fetching all team stats for team_id: ef6e2395...
Fetching all team stats for team_id: 5081cb86...
Fetching all team stats for team_id: b6676fa6...
Fetching all team stats for team_id: df4dd786...
Fetching all team stats for team_id: c33c79f0...
Fetching all team stats for team_id: c92a66bd...
Fetching all team stats for team_id: cceb83f4...
Fetching all team stats for team_id: 13c90c23...
Fetching all team stats for team_id: 46440a01...
Fetching all team stats for team_id: 759aca64...
Fetching all team stats for team_id: 8efee725...
Fetching all team stats for team_id: 33823d0e...
Fetching all team stats for team_id: c1ee8a93...
Fetching all team stats for team_id: 4d3c04bb...
Fetching all team stats for team_id: 81c68b51...
Fetching all team stats for team_id: f796b713...
Fetching all team stats for team_id: b3c4daf8...
Fetching all team stats for team_id: 73e43f76...
Fetching all team stats for team_id: 4c3ecbda...
Fetching all team stats for team_id: f1e6e6eb...
Fetching all team stats for team_id: 7111b7be...
Fetching all team stats for team_id: 7d709080...
Fetching all team stats for team_id: f2623a99...
Fetching all team stats for team_id: a3b05ba3...
Fetching all team stats for team_id: 3f85909d...
Fetching all team stats for team_id: 1755ecc5...
Fetching all team stats for team_id: 237d18a6...
Fetching all team stats for team_id: bb752d17...
Fetching all team stats for team_id: 424e3bfd...
Fetching all team stats for team_id: 0c2daf49...
Fetching all team stats for team_id: 3cab079c...
Fetching all team stats for team_id: 0647f3a2...
Fetching all team stats for team_id: 4eda3060...
Fetching all team stats for team_id: 9439a3f9...
Fetching all team stats for team_id: 46ac7cfe...
Fetching all team stats for team_id: c4884ba5...
Fetching all team stats for team_id: 7cb34e11...
Fetching all team stats for team_id: a9138bda...
Fetching all team stats for team_id: 81a55a17...
Fetching all team stats for team_id: 1aada6ac...
Fetching all team stats for team_id: f391b1d8...
Fetching all team stats for team_id: 3ff6a75d...
Fetching all team stats for team_id: 1363c52a...
Fetching all team stats for team_id: ad72c399...
Fetching all team stats for team_id: d5f0955f...
Fetching all team stats for team_id: 3c3891e2...
Fetching all team stats for team_id: e147860e...
Fetching all team stats for team_id: 7c1b56f5...
Fetching all team stats for team_id: 530517e1...
Fetching all team stats for team_id: 224528c2...
Fetching all team stats for team_id: b5a371a4...
Fetching all team stats for team_id: 377bcff9...
Fetching all team stats for team_id: f2b59083...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 5f655d47...
Fetching all team stats for team_id: ed045c1c...
Fetching all team stats for team_id: 3f1e784c...
Fetching all team stats for team_id: b4e2dc9e...
Fetching all team stats for team_id: f15135e5...
Fetching all team stats for team_id: 8b670eaf...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 0d06f6c9...
Fetching all team stats for team_id: 340bb32a...
Fetching all team stats for team_id: dcc0b27a...
Fetching all team stats for team_id: d17f1e28...
Fetching all team stats for team_id: 30bdfe0f...
Fetching all team stats for team_id: bf9e0e2f...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 20d8e905...
Fetching all team stats for team_id: 8d3503c3...
Fetching all team stats for team_id: 4fab2646...
Fetching all team stats for team_id: ac2b1188...
Fetching all team stats for team_id: d0460f08...
Fetching all team stats for team_id: 919bd8f3...
Fetching all team stats for team_id: c8bcb4b8...
Fetching all team stats for team_id: e976d334...
Fetching all team stats for team_id: 11b7d45b...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 411405fb...
Fetching all team stats for team_id: 04eaa9bb...
Fetching all team stats for team_id: 6f818b78...
Fetching all team stats for team_id: 16266ea0...
Fetching all team stats for team_id: 72482b01...
Fetching all team stats for team_id: 04962efb...
Fetching all team stats for team_id: 7969324b...
Fetching all team stats for team_id: e1925222...
Fetching all team stats for team_id: f97333f3...
Fetching all team stats for team_id: b904fef9...
Fetching all team stats for team_id: 11392c0c...
Fetching all team stats for team_id: 9b93d911...
Fetching all team stats for team_id: d75e45cc...
Fetching all team stats for team_id: 3dc1ae16...
Fetching all team stats for team_id: 837eef0a...
Fetching all team stats for team_id: 4bffe0d4...
Fetching all team stats for team_id: e04fafdb...
Fetching all team stats for team_id: b3966eee...
Fetching all team stats for team_id: 4f365e0d...
Fetching all team stats for team_id: 18a24bd5...
Fetching all team stats for team_id: 72634b36...
Fetching all team stats for team_id: 737dc45b...
Fetching all team stats for team_id: 57bc62c9...
Fetching all team stats for team_id: 54a398dc...
Fetching all team stats for team_id: 62fcb2d0...
Fetching all team stats for team_id: 431b2c76...
Fetching all team stats for team_id: 83a6ab83...
Fetching all team stats for team_id: 578241c8...
Fetching all team stats for team_id: 97df87d6...
Fetching all team stats for team_id: 6292f070...
Fetching all team stats for team_id: a51ed9a7...
Fetching all team stats for team_id: 7509b4b0...
Fetching all team stats for team_id: 117c9911...
Fetching all team stats for team_id: b150e716...
Fetching all team stats for team_id: 6cd4b046...
Fetching all team stats for team_id: 83533902...
Fetching all team stats for team_id: 02aa2398...
Fetching all team stats for team_id: 02c60781...
Fetching all team stats for team_id: af40af95...
Fetching all team stats for team_id: 182ea138...
Fetching all team stats for team_id: 20269023...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 204b85b3...
Fetching all team stats for team_id: d139ace3...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: a9c3984f...
Fetching all team stats for team_id: 49266fe2...
Fetching all team stats for team_id: 5dfee484...
Fetching all team stats for team_id: 1589fdf6...
Fetching all team stats for team_id: 9d81bf14...
Fetching all team stats for team_id: 4c7e4887...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: eb96cdb0...
Fetching all team stats for team_id: 7e51cac0...
Fetching all team stats for team_id: 1df3c170...
Fetching all team stats for team_id: 95ba991c...
Fetching all team stats for team_id: 5149996e...
Fetching all team stats for team_id: 931e1c23...
Fetching all team stats for team_id: 53ea6ee8...
Fetching all team stats for team_id: 370b9731...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 9b13901b...
Fetching all team stats for team_id: be110f80...
Fetching all team stats for team_id: 5371afd6...
Fetching all team stats for team_id: 42b9f50c...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: e211bb4a...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: a4d8d2de...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 9c9dd22e...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: f875a661...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 85820ff3...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 38f63c39...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 403d25a8...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 98311c04...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: f9542973...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: e85f419c...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: fac1c735...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: fec7f759...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 86ad6ed2...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 0f720270...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: f5631b7c...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 3a1983b3...
Fetching all team stats for team_id: 23778ceb...
Fetching all team stats for team_id: 66eb9ee0...
Fetching all team stats for team_id: 4de11b22...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 219a6262...
Fetching all team stats for team_id: a5486bf4...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: ffeae873...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 95fd1cbb...
Fetching all team stats for team_id: 1039f7c4...
Fetching all team stats for team_id: 03b35a84...
Fetching all team stats for team_id: 9d80e635...
Fetching all team stats for team_id: 1f174013...
Fetching all team stats for team_id: adcf355a...
Fetching all team stats for team_id: 31c1762c...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 35be24bd...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 8d7a0984...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 9c9c171b...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 9d065f09...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 418896c9...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: b17f8e4e...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 9f2f2c5b...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: a436ba95...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 53c16658...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 79b49b02...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: ed1a46d6...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 4e35533b...
Fetching all team stats for team_id: 970ac0ff...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 760fd7da...
Fetching all team stats for team_id: 75d00443...
Fetching all team stats for team_id: 0dd2edd6...
Fetching all team stats for team_id: 6b61df07...
Fetching all team stats for team_id: 3ffbc451...
Fetching all team stats for team_id: 11afe0c0...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 2bb18d14...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 1c080294...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 1ddf0399...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: c6874712...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 236538bf...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: fab79cf1...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 55aaae9b...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 70e752d4...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 714e2230...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 2be6bd3c...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 8037f9a0...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: fe0d03aa...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 4dda6911...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 4dbeeb9f...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 1107be23...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 45f46cd0...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: e2d68d33...
No team stats for {team_id} because the team id does not exist. Please raise an issue!
Fetching all team stats for team_id: 44f601b7...

                                                                       value
team_id                                                             34bd3e4e
team                                                                     Pau
game_date                                                           20220102
team_vs                                                                Brive
team_vs_id                                                          d416d837
match_id                                                            5506371d
players                    [0c9e0b74, 0f204548, 1e8cb669, 2bca4a65, 461e0...
score                                                                   43.0
team_vs_score                                                            NaN
22m_entries                                                              0.0
22m_conversion                                                           0.0
line_breaks                                                              0.0
carries                                                                  0.0
kicks                                                                    0.0
post_contact_metres                                                      0.0
dominant_tackles                                                         0.0
tackles_made                                                             0.0
tackles_missed                                                           0.0
turnovers_won                                                            0.0
tackle_turnover                                                          0.0
tackle_offload_allowed                                                   0.0
ruck_speed_0_3_pct                                                       NaN
ruck_speed_3_6_pct                                                       NaN
ruck_speed_6_plus_pct                                                    NaN
rucks_won                                                               78.0
possession                                                              0.53
territory                                                               0.63
tries                                                                    4.0
conversions                                                              NaN
penalty_goals                                                            5.0
drop_goals                                                               NaN
clean_breaks                                                             4.0
defenders_beaten                                                        13.0
kicks_from_hand                                                         15.0
lineout_success                                                          NaN
lineouts_won                                                            10.0
mauls_won                                                                6.0
metres_carried                                                         263.0
offloads                                                                 NaN
passes                                                                 112.0
penalties_conceded                                                      10.0
red_cards                                                                0.0
scrums_won                                                               8.0
tackles                                                                 78.0
total_lineouts                                                          13.0
total_scrums                                                             NaN
turnovers_conceded                                                      15.0
yellow_cards                                                             1.0
penalty_tries                                                            NaN
try_assists                                                              NaN
turnovers                                                                NaN
conversion_goals                                                         4.0
kick_percent_success                                                     1.0
lineout_won_steal                                                        1.0
mauls_total                                                              6.0
meters_run                                                             263.0
missed_tackles                                                          14.0
offload                                                                  2.0
pc_possession_first                                                     0.56
pc_possession_second                                                     0.5
pc_territory_first                                                      0.64
pc_territory_second                                                     0.62
rucks_total                                                             82.0
runs                                                                    95.0
scrums_total                                                            10.0
total_free_kicks_conceded                                                1.0
turnover_knock_on                                                        8.0

                                                                       value
team_id                                                             34bd3e4e
team                                                                     Pau
game_date                                                           20220423
team_vs                                                 Stade Francais Paris
team_vs_id                                                          530517e1
match_id                                                            8552a1e0
players                    [0c9e0b74, 0df999d4, 1e8cb669, 24f7f475, 2bca4...
score                                                                   18.0
team_vs_score                                                            NaN
22m_entries                                                              0.0
22m_conversion                                                           0.0
line_breaks                                                              0.0
carries                                                                  0.0
kicks                                                                    0.0
post_contact_metres                                                      0.0
dominant_tackles                                                         0.0
tackles_made                                                             0.0
tackles_missed                                                           0.0
turnovers_won                                                            0.0
tackle_turnover                                                          0.0
tackle_offload_allowed                                                   0.0
ruck_speed_0_3_pct                                                       NaN
ruck_speed_3_6_pct                                                       NaN
ruck_speed_6_plus_pct                                                    NaN
rucks_won                                                               64.0
possession                                                              0.45
territory                                                               0.61
tries                                                                    2.0
conversions                                                              NaN
penalty_goals                                                            2.0
drop_goals                                                               NaN
clean_breaks                                                             6.0
defenders_beaten                                                        12.0
kicks_from_hand                                                         10.0
lineout_success                                                          NaN
lineouts_won                                                            11.0
mauls_won                                                                4.0
metres_carried                                                         345.0
offloads                                                                 NaN
passes                                                                 131.0
penalties_conceded                                                      11.0
red_cards                                                                0.0
scrums_won                                                               6.0
tackles                                                                102.0
total_lineouts                                                          17.0
total_scrums                                                             NaN
turnovers_conceded                                                      16.0
yellow_cards                                                             0.0
penalty_tries                                                            NaN
try_assists                                                              NaN
turnovers                                                                NaN
conversion_goals                                                         1.0
kick_percent_success                                                     0.5
lineout_won_steal                                                        0.0
mauls_total                                                              4.0
meters_run                                                             345.0
missed_tackles                                                          20.0
offload                                                                  9.0
pc_possession_first                                                     0.46
pc_possession_second                                                    0.45
pc_territory_first                                                      0.67
pc_territory_second                                                     0.54
rucks_total                                                             67.0
runs                                                                    86.0
scrums_total                                                             7.0
total_free_kicks_conceded                                                0.0
turnover_knock_on                                                       11.0